version: "3.7"

networks:
  default:
    name: dmz
    external: true

volumes:
  repos:

services:
  git-server:
    image: registry.meschberger.ch/fmeschbe/git-server:latest
    container_name: git-server
    hostname: git
    domainname: meschberger.ch
    restart: unless-stopped
    ports:
      - "8880:80"
    volumes:
      - repos:/var/lib/git
