networks:
  default:
    name: dmz
    external: true

volumes:
  registry:

services:
  registry:
    container_name: registry
    image: registry:2
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_PORT: 5000
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      OFF_REGISTRY_HTTP_PREFIX: /my/nested/registry/
    volumes:
      - ${VOLUME_ROOT}registry:/var/lib/registry

  registry_browser:
    container_name: registry-browser
    restart: unless-stopped
    image: klausmeyer/docker-registry-browser:latest
    ports:
      - 5001:8080
    environment:
      ENV_DOCKER_REGISTRY_HOST: "registry"
      ENV_DOCKER_REGISTRY_PORT: 5000
      ENABLE_COLLAPSE_NAMESPACES: "false"
      ENABLE_DELETE_IMAGES: "true"
      RAILS_RELATIVE_URL_ROOT: "/browser"
      SCRIPT_NAME: "/browser"
      DOCKER_REGISTRY_URL: http://registry:5000
      PUBLIC_REGISTRY_URL: registry.meschberger.ch
      SECRET_KEY_BASE: "${SECRET_KEY_BASE:?Missing value for SECRET_KEY_BASE - terminating}"
    depends_on:
      - registry
