version: "2"

networks:
  default:
    name: dmz
    external: true

volumes:
  data:

services:
  diun:
    image: crazymax/diun:latest
    restart: unless-stopped
    container_name: diun
    hostname: diun-fixit
    command: serve
    volumes:
      - "data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      TZ: "Europe/Zurich"
      LOG_LEVEL: "info"
      LOG_JSON: "false"
      DIUN_WATCH_SCHEDULE: "0 5 * * *"
      DIUN_WATCH_FIRSTCHECKNOTIF: "true"
      DIUN_NOTIF_WEBHOOK_METHOD: "POST"
      DIUN_NOTIF_WEBHOOK_ENDPOINT: "http://homeassistant.meschberger.ch:8123/api/webhook/diun"
      DIUN_NOTIF_WEBHOOK_HEADERS_CONTENT-TYPE: "application/json"
      DIUN_PROVIDERS_DOCKER: "true"
      DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: "true"
