version: "2.1"
networks:
  default:
    name: dmz
    external: true

volumes:
  config:
  library:

services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - config:/config
      - library:/books
    restart: unless-stopped
