version: "2.1"

#
# Debian has DNS stub on port 53 which must be disabled:
#
# sudo sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf
#
#
# Also the resolv.conf file must be ensured to be dynamically linked to the dynamically
# generated one (typically, this is already the case):
#
# sudo sh -c 'rm /etc/resolv.conf && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf'
#
# NOTE:
# This setup uses manual (explicit) IP address management as the Pi-Hole container must
# be configured to connected to the Unbound DNS container by stating the IP address as
# opposed to a domain name.
#

networks:
  default:
    name: dmz
    external: true
  pihole:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
          ip_range: 172.30.0.4/30 # 172.30.0.5 - 172.30.0.6

volumes:
  unbound:
  pihole:
  dnsmasq:

services:
  pihole:
    container_name: pi-hole
    image: 'pihole/pihole:latest'
    restart: unless-stopped
    ports:
      # Only expose the DNS Server to the host, the HTTP
      # Server is available on the dmz network for the proxy
      - '53:53'
      - '53:53/udp'
      # If the reverse proxy is not available, map the HTTP port for configuration
      # access. By default this port should not be mapped, though, as the web
      # control panel is accessible through the reverse proxy
      # - '28088:80'
    environment:
      PIHOLE_DNS_: "172.30.0.6"
      WEBPASSWORD: "elohip"
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    networks:
      default:
        aliases:
          - pihole
      pihole:
        ipv4_address: "172.30.0.5"
    depends_on:
      - unbound

  unbound:
    container_name: unbound-rpi
    image: 'mvance/unbound-rpi:latest'
    restart: unless-stopped
    volumes:
      - unbound:/opt/unbound/etc/unbound
    networks:
      pihole:
        ipv4_address: "172.30.0.6"
