version: "2.1"

#
# Debian has DNS stub on port 53 which must be disabled:
#
# sudo sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf
#
#
# Also the resolv.conf file must be ensured to be dynamically linked to the dynamically
# generated one (typically, this is already the case):
#
# sudo sh -c 'rm /etc/resolv.conf && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf'
#
# NOTE:
# This setup uses manual (explicit) IP address management as the Pi-Hole container must
# be configured to connected to the Unbound DNS container by stating the IP address as
# opposed to a domain name.
#

networks:
  default:
    # Refer to a specific defined network name in the docker
    # system. By default it will be 'dmz'.
    # Note: If the ${IP_ADDRESS} environment variable is used
    #       this network must be defined such as to contain
    #       the configured IP address !
    name: ${NETWORK:-dmz}
    external: true
  pihole:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
          ip_range: 172.30.0.4/30 # 172.30.0.5 - 172.30.0.6

volumes:
  unbound:
  pihole:
  dnsmasq:

services:
  pihole:
    container_name: pi-hole
    image: 'pihole/pihole:latest'
    hostname: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      # Only expose the DNS Server to the host, the HTTP
      # Server is available on the dmz network for the proxy
      - '53:53'
      - '53:53/udp'
      # By default Pi-Hole is intended to be exposed behind
      # a transparent proxy gateway such as nginx. In case
      # such a proxy is not available for some reason, set
      # compose environment variable WEB_MAP to a port
      # mapping to 80, e.g. "WEB_MAP=- '8080:80'"
      ${WEB_MAP}
    environment:
      PIHOLE_DNS_: "172.30.0.6"
      WEBPASSWORD: "${WEBPASSWORD:?WEBPASSWORD environment variable missing or not set}"
      DNSMASQ_LISTENING: "${DNSMASQ_LISTENING:-single}"
      DHCP_ACTIVE: "${DHCP_ACTIVE:-false}"
      DHCP_START: "${DHCP_START}"
      DHCP_END: "${DHCP_END}"
      DHCP_ROUTER: "${DHCP_ROUTER}"
      DHCP_LEASETIME: ${DHCP_LEASETIME:-24}
      TZ: "${TZ:-Europe/Zurich}"
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    networks:
      default:
        # optionally define a static IP address with an environment
        # variable such as
        #    IP_ADDRESS="192.168.15.2"
        # Note, that this requires the ${NETWORK} to be configured
        # with a valid network address block containing this address
        ipv4_address: "${IP_ADDRESS}"
      pihole:
        ipv4_address: "172.30.0.5"
    depends_on:
      - unbound

  unbound:
    container_name: unbound-rpi
    image: 'mvance/unbound-rpi:latest'
    restart: unless-stopped
    volumes:
      - unbound:/opt/unbound/etc/unbound
    networks:
      pihole:
        ipv4_address: "172.30.0.6"
