version: "2.1"

networks:
  default:
    name: dmz
    external: true

volumes:
  config:

services:
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
      - MEM_STARTUP=1024M #optional
      - VIRTUAL_HOST=unifi.meschberger.ch
    volumes:
      - config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      # - 8443:8443 # disabled as being proxied
      - 1900:1900/udp #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
