version: '2'

networks:
  plex:
    external: true

volumes:
  config:
  transcode:

services:
  plex:
    container_name: plex
    hostname: plex
    domainname: meschberger.ch
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    environment:
      - PUID=15000
      - PGID=15000
      - TZ=Europe/Zurich
      # PLEX_CLAIM is only required on first start to link
      # this plex instance to the plex.tv account
      - VERSION=public
      - PLEX_CLAIM="${PLEX_CLAIM}"
    networks:
      plex:
        ipv4_address: "192.168.1.192"
    volumes:
      - config:/config
      - transcode:/transcode
      - /var/srv/shares/media:/data
    devices:
      - "/dev/dri:/dev/dri"
